name: 'Parse config JSON'
description: 'Gets items from config JSON file and returns values for the actual run'
inputs:
    branch:
        description: 'name of the branch for which values from JSON config file should be obtained'
        required: true
    repositoryConfigPath:
        description: 'relative path to JSON config file'
        required: true
outputs:
    userName:
        description: 'userName'
    clientId:
        description: 'client Id'
    instanceUrl:
        description: 'URL of the instance'
    certificatePath:
        description: 'path to the certificate key'
    runDestructive:
        description: 'should the destructive changes be deployed'
runs:
    using: 'node16'
    main: 'index.js'
